name: final_app
description: final_app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.1.0
  
  provider: ^6.0.0
  flutter_launcher_icons: "^0.9.2"
  http: ^0.13.3
  firebase_core: "^1.7.0"
  cloud_firestore: "^2.5.3"



  

flutter_icons:
  android: true
  image_path: "assets/images/logo_app.png"
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun-Italic.ttf
        - asset: assets/fonts/Sarabun-Bold.ttf


